repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/grantjenks/blue
  rev: v0.9.1
  hooks: 
    - id: blue
      name: blue
      description: 'Blue: The somewhat less uncompromision Python code formatter'
      entry: blue
      language: python
      language_version: python3
      minimum_pre_commit_version: 2.9.2
      require_serial: true
      types_or: [python, pyi]